name: Deploy to developement environment
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
env:
  NOMAD_ADDR: ${{ secrets.DEV_NOMAD_ADDR }}
  VAULT_ADDR: ${{ secrets.DEV_VAULT_ADDR }}
  VAULT_USERNAME: ${{ secrets.DEV_SERVICE_DEPLOYER_USERNAME }}
  VAULT_PASSWORD: ${{ secrets.DEV_SERVICE_DEPLOYER_PASSWORD }}
  IMAGE_TAG: ghcr.io/${{ github.repository }}:${{ github.sha }}
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        submodules: "recursive"

      - name: Build service binary
        run: cargo build --release

      - name: Run unit tests
        run: cargo test --bins --lib --release -- --nocapture --test-threads 1

      - name: Build Docker image
        run: docker build -t $IMAGE_TAG -f Dockerfile .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to ghcr
        run: docker push $IMAGE_TAG

  deploy:
    runs-on: self-hosted
    needs: [build]
    steps:
      - name: Get Nomad token from Vault
        uses: hashicorp/vault-action@v2
        with:
          url: ${VAULT_ADDR}
          method: userpass
          username: ${VAULT_USERNAME}
          password: ${VAULT_PASSWORD}
          secrets: nomad/creds/${VAULT_USERNAME} secret_id | NOMAD_TOKEN ;

      - name: Update image tag nomad variable
        run: nomad var get /nomad/jobs/commerce | nomad var put -in=json -out=table - IMAGE=$IMAGE_TAG

      - name: Deploy job
        run: nomad job run -verbose service.nomad
