name: Deploy to developement environment
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
env:
  NOMAD_ADDR: ${{ secrets.DEV_NOMAD_ADDR }}
  IMAGE_TAG: ghcr.io/${{ github.repository }}:${{ github.sha }}
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Cache multiple paths
        uses: whywaita/actions-cache-s3@v2
        with:
          with:
            path: |
              ~/.cargo/bin/
              ~/.cargo/registry/index/
              ~/.cargo/registry/cache/
              ~/.cargo/git/db/
              target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          aws-s3-bucket: dev-github-actions-cargo-cache
          aws-access-key-id: ${{ secrets.DEV_S3_CARGO_CACHE_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_S3_CARGO_CACHE_SECRET_ACCESS_KEY }}
          aws-endpoint: https://0d78eb8c22ee83b01fa99dd3efb348ae.r2.cloudflarestorage.com

      - name: Build service binary
        run: cargo build --release

      - name: Run unit tests
        run: cargo test --bins --lib --release -- --nocapture --test-threads 1

      - name: Build Docker image
        run: docker build -t $IMAGE_TAG -f Dockerfile .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to ghcr
        run: docker push $IMAGE_TAG

  deploy:
    runs-on: self-hosted
    needs: [build]
    steps:
      - name: Get Nomad token from Vault
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.DEV_VAULT_ADDR }}
          method: userpass
          username: ${{ secrets.DEV_SERVICE_DEPLOYER_USERNAME }}
          password: ${{ secrets.DEV_SERVICE_DEPLOYER_PASSWORD }}
          secrets: nomad/creds/${{ secrets.DEV_SERVICE_DEPLOYER_USERNAME }} secret_id | NOMAD_TOKEN ;

      - name: Update image tag nomad variable
        run: nomad var get /nomad/jobs/commerce | nomad var put -in=json -out=table - IMAGE=$IMAGE_TAG

      - name: Deploy job
        run: nomad job run -verbose service.nomad
